spring:
  datasource:
    url: jdbc:postgresql://sentinela-db-nexus-gaming.l.aivencloud.com:21349/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_a-Mik1Nd0Et46eNcU-R
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
